version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.16
    working_directory: ~/eventuate-plugins-gradle
    steps:
      - checkout
      - restore_cache:
          keys:
            - eventuate-plugins-gradle-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - eventuate-plugins-gradle-
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-plugins-gradle-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - run: TERM=dumb ./gradlew build
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./gradlew publishEventuateArtifacts
          when: on_success
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          context:
            - publish
